### ISSUE TITLE
Please help, lightgallery is not a function using lastest 1.3.9

### ISSUE THREAD

**Issue by Borming** [sachinchoolur/lightGallery#571]
I am using Lightgallery via NPM, and using it in ES6 project via import

import lightgallery from "lightgallery"

this used to work in 1.3.2, but when i updated to 1.3.9 i am getting an error "lightGallery is not a function". This means that lightgallery is not attached to jquery, but jquery is attached to window.$ and window.jQuery way before lightGallery is imported.

Can someone please help with this?

**Comment by sachinchoolur** [comment]
Hey @Borming ,

The bellow code works fine for me.
``` js

import $ from 'jquery';
import jQuery from 'jquery';

window.$ = $;
window.jQuery = jQuery;

import "lightGallery";

$('#lightgallery').lightGallery();

```

Let me know if you need a demo.

**Comment by jonathanrbowman** [comment]
I found this question while investigating a change I recently needed to make. Lightgallery wasn't a function for me because the lightgallery file name changed from `lightgallery-all.min.js` to `lightgallery.min.js`.

This was in a project I didn't originally set up, so I don't know if this is what was happening for you but it's what was happening for me, and changing the `script` tag to point to `lightgallery.min.js` got everything working again.

**Comment by CrashyBang** [comment]
Hey @sachinchoolur I have tried your above code with 1.3.9 and I am having no luck I get:

```
lightGallery is not defined
```

I have made sure jQuery is available well before I try to load in lightGallery.

Using Webpack 2 to bundle.

Cheers.

**Comment by jonathanrbowman** [comment]
Do you get a 404 trying to load lightgallery?

**Comment by CrashyBang** [comment]
I have install lightgallery via NPM so I am not loading it over a CDN if that is what you mean.

Cheers.

**Comment by jonathanrbowman** [comment]
Sorry if I'm talking outside of my depth, but don't you still have to link to the script somewhere in your HTML, even if downloaded via NPM?

**Comment by CrashyBang** [comment]
Hey @jonathanrbowman sorry I see what you are saying, I have 'bundled' lightGallery into one big JS file called app.js which is being required.

Either way I switched over to `lightgallery.js` which is a vanilla JS rewrite and that has resolved the issue.
